Forward GREP to grep on case-insensitive filesystems
When grep is invoked on a case-insensitive filesystem, and PATH contains
the tests/bin directory, then GREP will be used, causing all kinds of
confusion.

Detect this case and redirect to system grep instead.

While we are at it, add some tests for GREP.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

diff --git a/tests/bin/GREP b/tests/bin/GREP
--- a/tests/bin/GREP
+++ b/tests/bin/GREP
@@ -1,11 +1,44 @@
 #!/bin/sh
-test -f /bin/grep && grep=/bin/grep
-test -f /usr/bin/grep && grep=/usr/bin/grep
 
-input="$(cat)"
-if echo "$input" | "$grep" -q "$@"; then
-	exit 0
+# Find the system grep, taking precautions not to pick this script again.
+IFS=:
+self_dev_ino=$(stat -f "%d/%i" "$0")
+for dir in $PATH; do
+	if [ -x "$dir/grep" ] && [ "$self_dev_ino" != "$(stat -f "%d/%i" "$dir/grep")" ]; then
+		grep="$dir/grep"
+		break
+	fi
+done
+unset IFS
+test -n "$grep" || ( echo "GREP: cannot find system grep"; exit 1 )
+
+# If a case-insensitive filesystem picked this script over the system grep
+# implementation, execute the system grep.
+if [ "$(basename "$0")" = grep ]; then
+	exec "$grep" "$@"
 fi
+
+# Make sure we have the pattern or any other arguments given.
+if [ $# -eq 0 ]; then
+	echo "usage: GREP [options] [pattern] [file ...]"
+	exit
+fi
+
+# Make sure that we are not accidentally reading from a tty.
+if [ -t 0 ]; then
+	echo "GREP: refusing to match terminal input"
+	exit 1
+fi
+
+# Read the input to a temporary buffer.
+input="$(cat)"
+
+# If the input matches the given pattern, we're all set.
+if echo "$input" | "$grep" -q "$@"; then
+	exit
+fi
+
+# Display information about failed match, along with the input and the pattern.
 printf 'GREP: failed to match: grep'
 for arg in "$@"; do
 	printf " '%s'" "$(echo "$arg" | sed -e "s/'/\\'/g")"
